import Foundation
import GMCCDaemonKit

/// PING — liveness + build identity. The protocol-version handshake itself
/// runs in Server.dispatch before any handler; this reports the stamped
/// BuildInfo (generated by build_daemon.sh) so staleness is observable.
enum PingHandler {
    static func handle(head: EnvelopeHead, startedAt: String, startedDate: Date) throws -> HandlerResult {
        let response = PingResponse(
            daemonPid: getpid(),
            protocolVersion: GMCCWireProtocol.version,
            buildSha: BuildInfo.sha,
            buildDate: BuildInfo.date,
            startedAt: startedAt,
            uptimeSeconds: Int(Date().timeIntervalSince(startedDate))
        )
        return try okResult(.ping, head, response)
    }
}
