// GENERATED by gm_kernel bridge --roster-out from AgenticsCore/Tools — do not
// edit; regenerate with gmk/scripts/generate_plugin.sh

enum CdeToolRoster {
    static let json: String = #"""
        [
          {
            "always_load" : true,
            "description" : "The doped record of the code: search this session's dope tree, search every project's, or write a scope back to its repo.",
            "name" : "cde_dope",
            "ops" : [
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes"
                  ],
                  "retryWith" : "cde_dope op=search_session with cursor = page.next_cursor"
                },
                "op" : "search_session",
                "required_params" : [
                  "query"
                ],
                "summary" : "FTS over the session's dope tree (hits carry dot-paths).",
                "verbs" : [
                  "DOPE_SEARCH"
                ]
              },
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes"
                  ],
                  "retryWith" : "cde_dope op=search_global with cursor = page.next_cursor"
                },
                "op" : "search_global",
                "required_params" : [
                  "query"
                ],
                "summary" : "FTS over the dope trees of ALL projects and sessions, not just this one.",
                "verbs" : [
                  "DOPE_SEARCH"
                ]
              },
              {
                "is_write" : true,
                "op" : "update_session",
                "required_params" : [
                  "scope_uuid"
                ],
                "summary" : "Write the session's dope tree back to its repo — many dope nodes to disk at once.",
                "verbs" : [
                  "DOPE_WRITE_REPO"
                ]
              }
            ],
            "refuses" : false,
            "schema" : {
              "properties" : {
                "cursor" : {
                  "description" : "page.next_cursor from the previous call (opaque) — omit for the first page",
                  "type" : "string"
                },
                "force" : {
                  "description" : "Write even when the repo has diverged",
                  "type" : "boolean"
                },
                "limit" : {
                  "description" : "How many hits to return, 1 to 500.",
                  "type" : "integer"
                },
                "op" : {
                  "description" : "Which dope door to use.",
                  "enum" : [
                    "search_session",
                    "search_global",
                    "update_session"
                  ],
                  "type" : "string"
                },
                "page_bytes" : {
                  "description" : "Page budget in bytes (default 30000, max 45000); every array and every long text is paged inside it",
                  "type" : "integer"
                },
                "prompt_uuid" : {
                  "description" : "Prompt scope selector",
                  "type" : "string"
                },
                "query" : {
                  "description" : "Words to look for. Whole words match; misspellings find nothing.",
                  "type" : "string"
                },
                "scope" : {
                  "description" : "prompt|session|project (default session)",
                  "type" : "string"
                },
                "scope_uuid" : {
                  "description" : "The dope scope to write",
                  "type" : "string"
                },
                "session_uuid" : {
                  "description" : "Explicit session uuid",
                  "type" : "string"
                }
              },
              "required" : [
                "op"
              ],
              "type" : "object"
            }
          },
          {
            "always_load" : true,
            "description" : "Tell me who I am and what I am working on.",
            "name" : "cde_init",
            "ops" : [
              {
                "is_write" : true,
                "op" : "run",
                "required_params" : [

                ],
                "summary" : "The cold start: resolve project, instance and session from the working directory, resolve or create the prompt, and answer with the phase, its instructions and the briefing's state.",
                "verbs" : [
                  "CONTEXT_ENSURE",
                  "PROMPT_LIST",
                  "PROMPT_CREATE",
                  "PROMPT_RESUME",
                  "BOT_NEXT",
                  "BRIEFING_GET"
                ]
              }
            ],
            "refuses" : false,
            "schema" : {
              "properties" : {
                "create" : {
                  "description" : "Create the prompt when the selector matches nothing. Requires name and detail — a typo must never create a prompt.",
                  "type" : "boolean"
                },
                "detail" : {
                  "description" : "Detail text for a newly created prompt (with create). STAY TRUE: the user's passed prompt, verbatim.",
                  "type" : "string"
                },
                "name" : {
                  "description" : "Name for a newly created prompt (with create).",
                  "type" : "string"
                },
                "op" : {
                  "description" : "The only op: fold identity, prompt and briefing into one answer.",
                  "enum" : [
                    "run"
                  ],
                  "type" : "string"
                },
                "selector" : {
                  "description" : "Prompt seq (10), code (p10), exact name, or a unique fragment of a name.",
                  "type" : "string"
                },
                "variant" : {
                  "description" : "Workflow variant: bot | rpi | team (default bot).",
                  "type" : "string"
                }
              },
              "required" : [
                "op"
              ],
              "type" : "object"
            }
          },
          {
            "always_load" : true,
            "description" : "Pre-indexed external knowledge: search digested kbite files, open a maw to collect raw sources, digest a chewed maw.",
            "name" : "cde_kbite",
            "ops" : [
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes",
                    "limit"
                  ],
                  "retryWith" : "cde_kbite op=search with cursor = page.next_cursor"
                },
                "op" : "search",
                "required_params" : [
                  "query"
                ],
                "summary" : "bm25-ranked kbite file stubs with briefs — read the briefs first.",
                "verbs" : [
                  "KBITE_SEARCH"
                ]
              },
              {
                "is_write" : true,
                "op" : "open_maw",
                "required_params" : [
                  "kbite_name",
                  "maw_path"
                ],
                "summary" : "Open a maw — the staging directory a kbite's raw sources are collected into before they are chewed and digested.",
                "verbs" : [
                  "KBITE_MAW_OPEN"
                ]
              },
              {
                "is_write" : true,
                "op" : "digest",
                "required_params" : [
                  "code",
                  "kbite_open_path"
                ],
                "summary" : "Digest a chewed maw into the database and archive its raw sources.",
                "verbs" : [
                  "KBITE_DIGEST"
                ]
              }
            ],
            "refuses" : false,
            "schema" : {
              "properties" : {
                "code" : {
                  "description" : "The kbite code being digested. digest only.",
                  "type" : "string"
                },
                "cursor" : {
                  "description" : "Page cursor from the previous answer's page.next_cursor.",
                  "type" : "string"
                },
                "kbite_name" : {
                  "description" : "The kbite this maw feeds. open_maw only.",
                  "type" : "string"
                },
                "kbite_open_path" : {
                  "description" : "The opened maw's path. digest only.",
                  "type" : "string"
                },
                "limit" : {
                  "description" : "How many hits to return, 1 to 500. search only.",
                  "type" : "integer"
                },
                "maw_path" : {
                  "description" : "Where the maw lives on disk. open_maw only.",
                  "type" : "string"
                },
                "op" : {
                  "description" : "Which kbite move to make.",
                  "enum" : [
                    "search",
                    "open_maw",
                    "digest"
                  ],
                  "type" : "string"
                },
                "page_bytes" : {
                  "description" : "Page budget in bytes.",
                  "type" : "integer"
                },
                "query" : {
                  "description" : "Words to look for. Whole words match; misspellings find nothing. search only.",
                  "type" : "string"
                }
              },
              "required" : [
                "op"
              ],
              "type" : "object"
            }
          },
          {
            "always_load" : true,
            "description" : "The workflow's prompt: read it without being told a uuid, list prompts, edit a draft's backstory / goal / detail, move it through draft → initiated → done, or read the file changes recorded against it. Long text arrives as windows — loop on cursor until page.next_cursor is null.",
            "name" : "cde_prompt",
            "ops" : [
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes"
                  ],
                  "retryWith" : "cde_prompt op=load with cursor = page.next_cursor"
                },
                "op" : "load",
                "required_params" : [

                ],
                "summary" : "The prompt this workflow is on. Reading it never advances it; its detail, backstory and goal arrive as text windows.",
                "verbs" : [
                  "BOT_GET",
                  "PROMPT_GET"
                ]
              },
              {
                "is_write" : false,
                "op" : "list",
                "required_params" : [

                ],
                "summary" : "The session's prompts, narrowed by an optional selector.",
                "verbs" : [
                  "PROMPT_LIST"
                ]
              },
              {
                "is_write" : true,
                "op" : "draft",
                "required_params" : [
                  "prompt_uuid",
                  "expected_version"
                ],
                "summary" : "Edit a DRAFT prompt's stay-true triple. The daemon refuses once the prompt has left draft, so re-open it first.",
                "verbs" : [
                  "PROMPT_UPDATE_CONTENT"
                ]
              },
              {
                "is_write" : true,
                "op" : "set_status",
                "required_params" : [
                  "prompt_uuid",
                  "expected_version",
                  "status"
                ],
                "summary" : "THE ONLY DOOR THAT MOVES A PROMPT, and it claims or releases the prompt's activation for this instance. It creates no summaries. Primary only.",
                "verbs" : [
                  "PROMPT_SET_STATUS"
                ]
              },
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes",
                    "path",
                    "limit"
                  ],
                  "retryWith" : "cde_prompt op=file_changes with cursor = page.next_cursor; path for one file"
                },
                "op" : "file_changes",
                "required_params" : [

                ],
                "summary" : "READ ONLY: what the machine believes you have touched. Capture belongs to the PostToolUse hook, so there is no op here that writes one.",
                "verbs" : [
                  "FILE_CHANGE_LIST"
                ]
              }
            ],
            "refuses" : false,
            "schema" : {
              "properties" : {
                "backstory" : {
                  "description" : "draft: the prompt's backstory. Leave it out to leave it alone.",
                  "type" : "string"
                },
                "cursor" : {
                  "description" : "Page cursor from the previous call's page.next_cursor; leave it out for the first page.",
                  "type" : "string"
                },
                "detail" : {
                  "description" : "draft: the prompt's detail. Leave it out to leave it alone.",
                  "type" : "string"
                },
                "expected_version" : {
                  "description" : "draft, set_status: version of the prompt you read, so two writers cannot clobber each other.",
                  "type" : "integer"
                },
                "goal" : {
                  "description" : "draft: the prompt's goal. Leave it out to leave it alone.",
                  "type" : "string"
                },
                "limit" : {
                  "description" : "file_changes: how many rows to consider, newest first.",
                  "type" : "integer"
                },
                "op" : {
                  "description" : "What to do with the prompt: read it, list prompts, edit a draft, move it, or read its file changes.",
                  "enum" : [
                    "load",
                    "list",
                    "draft",
                    "set_status",
                    "file_changes"
                  ],
                  "type" : "string"
                },
                "page_bytes" : {
                  "description" : "Page budget in bytes; every array and every long text is paged inside it.",
                  "type" : "integer"
                },
                "path" : {
                  "description" : "file_changes: only changes to this repo-relative path. Leave it out for every file.",
                  "type" : "string"
                },
                "prompt_uuid" : {
                  "description" : "Which prompt to read or write, by uuid. Leave it out to use the prompt this session is on.",
                  "type" : "string"
                },
                "selector" : {
                  "description" : "list: which prompts — a number like 1, a code like p10, or a unique piece of a name. Leave it out to list them all.",
                  "type" : "string"
                },
                "session_uuid" : {
                  "description" : "list, file_changes: which session. Leave it out for the session this working directory resolves to.",
                  "type" : "string"
                },
                "status" : {
                  "description" : "set_status: where to move it — 'initiated' to start, 'done' to finish, or 'draft' to send a finished prompt back for editing.",
                  "enum" : [
                    "draft",
                    "initiated",
                    "done"
                  ],
                  "type" : "string"
                }
              },
              "required" : [
                "op"
              ],
              "type" : "object"
            }
          },
          {
            "always_load" : false,
            "description" : "The architecture phase: open the plan page, write one option per methodology, expand the persistence, field and general change rows, write the narrative, run the plan gate (propose → approve or revise), record the decision, and read the plan back.",
            "name" : "cde_rpir_architecture",
            "ops" : [
              {
                "is_write" : true,
                "op" : "open",
                "required_params" : [
                  "prompt_uuid"
                ],
                "summary" : "Open the prompt's architecture summary page — fetch-or-open, idempotent. Opened explicitly like every summary; nothing opens it as a side effect.",
                "verbs" : [
                  "ARCH_OPEN"
                ]
              },
              {
                "is_write" : true,
                "op" : "open_option",
                "required_params" : [
                  "summary_uuid",
                  "agent_name",
                  "body"
                ],
                "summary" : "Write YOUR methodology's option row (one per agent_name). To REVISE a proposal, pass supersedes_option_uuid + expected_version together.",
                "verbs" : [
                  "ARCH_OPTION_ADD"
                ]
              },
              {
                "is_write" : true,
                "op" : "write_persistence",
                "required_params" : [
                  "summary_uuid",
                  "class_name",
                  "file_path",
                  "reason_brief"
                ],
                "summary" : "Record ONE persistence-tier change. Persistence rows come before general rows because a schema or wire delta is what the plan gate is signed off against.",
                "verbs" : [
                  "ARCH_PERSIST_ADD"
                ]
              },
              {
                "is_write" : true,
                "op" : "write_field",
                "required_params" : [
                  "persistence_change_uuid",
                  "field_name",
                  "data_type",
                  "change_reason",
                  "change_purpose",
                  "nullable"
                ],
                "summary" : "Record ONE field-level change under a persistence change row.",
                "verbs" : [
                  "ARCH_FIELD_ADD"
                ]
              },
              {
                "is_write" : true,
                "op" : "write_general",
                "required_params" : [
                  "summary_uuid",
                  "file_path",
                  "reason_brief",
                  "change_depth",
                  "change_code"
                ],
                "summary" : "Record ONE general (non-persistence) change. change_depth is pseudo|draft|actual — draft is a planned change not yet written.",
                "verbs" : [
                  "ARCH_GENERAL_ADD"
                ]
              },
              {
                "is_write" : true,
                "op" : "summarize",
                "required_params" : [
                  "summary_uuid",
                  "expected_version",
                  "body"
                ],
                "summary" : "Write the architecture summary's own body — the plan narrative over the expanded rows.",
                "verbs" : [
                  "ARCH_SUMMARIZE"
                ]
              },
              {
                "is_write" : true,
                "op" : "propose",
                "required_params" : [
                  "summary_uuid",
                  "expected_version"
                ],
                "summary" : "drafting → proposed: put the expanded plan on the table for the plan gate.",
                "verbs" : [
                  "ARCH_PROPOSE"
                ]
              },
              {
                "is_write" : true,
                "op" : "approve",
                "required_params" : [
                  "summary_uuid",
                  "expected_version"
                ],
                "summary" : "proposed → approved (terminal; unlocks implementation). The user's sign-off at the plan gate is what authorizes this call.",
                "verbs" : [
                  "ARCH_APPROVE"
                ]
              },
              {
                "is_write" : true,
                "op" : "revise",
                "required_params" : [
                  "summary_uuid",
                  "expected_version"
                ],
                "summary" : "proposed → drafting: the revision edge. Reopens the summary so options and rows can change; compose with open_option's supersede form to replace a proposal.",
                "verbs" : [
                  "ARCH_REVISE"
                ]
              },
              {
                "is_write" : true,
                "narrowing" : {
                  "parameters" : [

                  ],
                  "retryWith" : "cde_rpir_architecture op=get (the decision and its rationale are on the summary; pass option_uuid for one option's body)"
                },
                "op" : "decide",
                "required_params" : [
                  "option_uuid",
                  "expected_version",
                  "rationale"
                ],
                "summary" : "Select ONE option. Stamps it selected, rejects every sibling, and records why in one atomic write. Only the selected option may expand into change rows. Primary only.",
                "verbs" : [
                  "ARCH_DECIDE"
                ]
              },
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes",
                    "option_uuid",
                    "change_uuid"
                  ],
                  "retryWith" : "cde_rpir_architecture op=get with cursor = page.next_cursor; option_uuid / change_uuid for one body"
                },
                "op" : "get",
                "required_params" : [
                  "prompt_uuid"
                ],
                "summary" : "The approved architecture with its implementation state: persistence changes (whole) before general change stubs, each joined to its recorded file changes. Long text arrives as windows; loop on cursor until page.next_cursor is null.",
                "verbs" : [
                  "ARCH_GET"
                ]
              }
            ],
            "refuses" : false,
            "schema" : {
              "properties" : {
                "agent_id" : {
                  "description" : "Your own agent id, so two agents cannot share one list.",
                  "type" : "string"
                },
                "agent_name" : {
                  "description" : "Your methodology name. One plan per methodology.",
                  "type" : "string"
                },
                "body" : {
                  "description" : "The prose body: your whole proposal on open_option, the plan narrative on summarize.",
                  "type" : "string"
                },
                "change_code" : {
                  "description" : "The instruction whoever implements this will follow. Write it to them, not about them.",
                  "type" : "string"
                },
                "change_depth" : {
                  "description" : "How worked-out this code change is.",
                  "enum" : [
                    "pseudo",
                    "draft",
                    "actual"
                  ],
                  "type" : "string"
                },
                "change_kind" : {
                  "description" : "What is happening to it.",
                  "enum" : [
                    "add",
                    "modify",
                    "rename",
                    "delete"
                  ],
                  "type" : "string"
                },
                "change_purpose" : {
                  "description" : "What the change is for.",
                  "type" : "string"
                },
                "change_reason" : {
                  "description" : "Why this field is changing.",
                  "type" : "string"
                },
                "change_uuid" : {
                  "description" : "Read one change in full, by uuid. Leave it out for short versions of all.",
                  "type" : "string"
                },
                "class_name" : {
                  "description" : "Name of the class, type or table being changed.",
                  "type" : "string"
                },
                "cursor" : {
                  "description" : "page.next_cursor from the previous call. Leave it out for the first page.",
                  "type" : "string"
                },
                "data_type" : {
                  "description" : "Type of the field.",
                  "type" : "string"
                },
                "dope_property_ref" : {
                  "description" : "For the property. Dot-path CODES like `domain.entity.property`. Never uuids, never file paths.",
                  "type" : "string"
                },
                "dope_ref" : {
                  "description" : "For the entity. Dot-path CODES like `domain.entity.property`. Never uuids, never file paths.",
                  "type" : "string"
                },
                "expected_version" : {
                  "description" : "The version you based this write on. On a conflict, re-read, take the new version and retry — that is a normal outcome, not a failure.",
                  "type" : "integer"
                },
                "field_name" : {
                  "description" : "Name of the field.",
                  "type" : "string"
                },
                "file_path" : {
                  "description" : "Repo-relative file this change owns.",
                  "type" : "string"
                },
                "fk_target" : {
                  "description" : "What the field points at, only when is_foreign_key.",
                  "type" : "string"
                },
                "is_foreign_key" : {
                  "description" : "True if the field points at another table.",
                  "type" : "boolean"
                },
                "is_indexed" : {
                  "description" : "True if the field is indexed.",
                  "type" : "boolean"
                },
                "limit" : {
                  "description" : "Cap the general change stub roster to its first N rows.",
                  "type" : "integer"
                },
                "nullable" : {
                  "description" : "True if the field may be null.",
                  "type" : "boolean"
                },
                "op" : {
                  "description" : "Which architecture step to take.",
                  "enum" : [
                    "open",
                    "open_option",
                    "write_persistence",
                    "write_field",
                    "write_general",
                    "summarize",
                    "propose",
                    "approve",
                    "revise",
                    "decide",
                    "get"
                  ],
                  "type" : "string"
                },
                "option_uuid" : {
                  "description" : "Which plan, by option uuid: the one to select on decide, one body to read on get.",
                  "type" : "string"
                },
                "page_bytes" : {
                  "description" : "Page budget in bytes (default 30000, max 45000).",
                  "type" : "integer"
                },
                "persistence_change_uuid" : {
                  "description" : "The database change row these fields belong to, by uuid.",
                  "type" : "string"
                },
                "prompt_uuid" : {
                  "description" : "Which prompt this architecture belongs to, by uuid.",
                  "type" : "string"
                },
                "rationale" : {
                  "description" : "Why this plan won, and what the rejected ones still contribute. A decision with no reasoning gets argued again later.",
                  "type" : "string"
                },
                "reason_brief" : {
                  "description" : "Why this change, in one or two sentences, and what it costs.",
                  "type" : "string"
                },
                "renamed_from" : {
                  "description" : "Old field name, only when change_kind is rename.",
                  "type" : "string"
                },
                "summary_uuid" : {
                  "description" : "Which architecture to write to, by summary uuid.",
                  "type" : "string"
                },
                "supersedes_option_uuid" : {
                  "description" : "Option this proposal REPLACES, by uuid. Leave it out for a new proposal. The old row stays as rejected history, and if it was the selected plan the new one takes the selection. Needs expected_version.",
                  "type" : "string"
                }
              },
              "required" : [
                "op"
              ],
              "type" : "object"
            }
          },
          {
            "always_load" : false,
            "description" : "The briefing page: open it for a briefer, write its dope/kbite/file-change ref set, seal it, and read it back.",
            "name" : "cde_rpir_briefing",
            "ops" : [
              {
                "is_write" : true,
                "op" : "open",
                "required_params" : [
                  "prompt_uuid"
                ],
                "summary" : "Open the briefing row a briefer then fills. The only legal response to the 'initial briefing not ready' gate blocker, and the very next call after cde_init for a prompt whose briefing is absent.",
                "verbs" : [
                  "BRIEFING_OPEN"
                ]
              },
              {
                "is_write" : true,
                "op" : "write",
                "required_params" : [
                  "briefing_uuid",
                  "expected_version",
                  "dope_refs",
                  "kbite_refs",
                  "file_change_refs"
                ],
                "summary" : "building → ready: write the briefing's ref set (opinion-free; the daemon stamps staleness + kbite briefs). ALL THREE ref classes are REQUIRED of you: a briefing records what it LOOKED FOR, not only what it found. Pass [] for a class you searched and came up empty on — that is a real answer. Omitting a class is refused, because absent is indistinguishable from never having looked.",
                "verbs" : [
                  "BRIEFING_COMPLETE"
                ]
              },
              {
                "is_write" : true,
                "op" : "close",
                "required_params" : [
                  "briefing_uuid",
                  "expected_version",
                  "dope_refs",
                  "kbite_refs",
                  "file_change_refs"
                ],
                "summary" : "Seal the briefing — the briefer's page is done and the agent can go away. Same verb as op=write: BRIEFING_COMPLETE both writes the ref set and moves building → ready.",
                "verbs" : [
                  "BRIEFING_COMPLETE"
                ]
              },
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes"
                  ],
                  "retryWith" : "cde_rpir_briefing op=load with cursor = page.next_cursor"
                },
                "op" : "load",
                "required_params" : [

                ],
                "summary" : "Fetch a briefing + staleness. Zero-uuid form: pass only step and YOUR briefing resolves.",
                "verbs" : [
                  "BRIEFING_GET"
                ]
              }
            ],
            "refuses" : false,
            "schema" : {
              "properties" : {
                "agent_id" : {
                  "description" : "Your own agent id, so two agents cannot share one list.",
                  "type" : "string"
                },
                "briefing_uuid" : {
                  "description" : "Which briefing to write to, by summary uuid. Required by write and close.",
                  "type" : "string"
                },
                "cursor" : {
                  "description" : "page.next_cursor from the previous call (opaque) — omit for the first page. Load only.",
                  "type" : "string"
                },
                "dope_refs" : {
                  "description" : "Dot-path CODES like `domain.entity.property`. Never uuids, never file paths. An empty list means you looked and found none, which is an answer. An omitted list is refused — absent is indistinguishable from never having looked.",
                  "items" : {
                    "type" : "string"
                  },
                  "type" : "array"
                },
                "expected_version" : {
                  "description" : "The version you based this write on. On a conflict, re-read, take the new version and retry — that is a normal outcome, not a failure.",
                  "type" : "integer"
                },
                "file_change_refs" : {
                  "description" : "File change uuids. An empty list means you looked and found none, which is an answer. An omitted list is refused — absent is indistinguishable from never having looked.",
                  "items" : {
                    "type" : "string"
                  },
                  "type" : "array"
                },
                "kbite_refs" : {
                  "description" : "Kbite file uuids, not codes and not paths. An empty list means you looked and found none, which is an answer. An omitted list is refused — absent is indistinguishable from never having looked.",
                  "items" : {
                    "type" : "string"
                  },
                  "type" : "array"
                },
                "op" : {
                  "description" : "Which briefing move to make.",
                  "enum" : [
                    "open",
                    "write",
                    "close",
                    "load"
                  ],
                  "type" : "string"
                },
                "page_bytes" : {
                  "description" : "Page budget in bytes (default 30000, max 45000); every array and every long text is paged inside it. Load only.",
                  "type" : "integer"
                },
                "prompt_uuid" : {
                  "description" : "Which prompt the briefing belongs to, by uuid. Required by open.",
                  "type" : "string"
                },
                "step" : {
                  "description" : "Which briefing step. 'initial' is the only accepted value; the daemon rejects anything else.",
                  "type" : "string"
                }
              },
              "required" : [
                "op"
              ],
              "type" : "object"
            }
          },
          {
            "always_load" : false,
            "description" : "The clarification record: questions for the human, private notes, their answers, and the care package that carries the decided intent forward.",
            "name" : "cde_rpir_clarify",
            "ops" : [
              {
                "is_write" : true,
                "op" : "open",
                "required_params" : [
                  "prompt_uuid"
                ],
                "summary" : "Open the prompt's clarification summary. No status move — the prompt is already initiated.",
                "verbs" : [
                  "CLARIFY_OPEN"
                ]
              },
              {
                "is_write" : true,
                "op" : "write_questions",
                "required_params" : [
                  "summary_uuid",
                  "question"
                ],
                "summary" : "Insert ONE user-facing question with its ordered options, while the summary is building.",
                "verbs" : [
                  "CLARIFY_QUESTION_ADD"
                ]
              },
              {
                "is_write" : true,
                "op" : "write_notes",
                "required_params" : [
                  "summary_uuid",
                  "body"
                ],
                "summary" : "Insert ONE internal note, weighted 0 (critical) to 999 (ignore), in any summary state.",
                "verbs" : [
                  "CLARIFY_NOTE_ADD"
                ]
              },
              {
                "is_write" : true,
                "op" : "answer",
                "required_params" : [
                  "question_uuid",
                  "expected_version"
                ],
                "summary" : "Record the user's answer to ONE question, or mark it skipped.",
                "verbs" : [
                  "CLARIFY_ANSWER"
                ]
              },
              {
                "is_write" : true,
                "op" : "seal",
                "required_params" : [
                  "summary_uuid",
                  "expected_version"
                ],
                "summary" : "building → answering. Answers are writable only after this seal. The primary's call.",
                "verbs" : [
                  "CLARIFY_SEAL"
                ]
              },
              {
                "is_write" : true,
                "op" : "finalize",
                "required_params" : [
                  "summary_uuid",
                  "expected_version"
                ],
                "summary" : "answering → complete, once every question is answered or skipped. The LATER move, after seal.",
                "verbs" : [
                  "CLARIFY_FINALIZE"
                ]
              },
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes",
                    "note_uuid"
                  ],
                  "retryWith" : "cde_rpir_clarify op=get with cursor = page.next_cursor; note_uuid for one body"
                },
                "op" : "get",
                "required_params" : [

                ],
                "summary" : "The summary, its questions with answers, and its notes. The package stays a stub.",
                "verbs" : [
                  "CLARIFY_GET"
                ]
              },
              {
                "is_write" : true,
                "op" : "package_open",
                "required_params" : [
                  "summary_uuid"
                ],
                "summary" : "Open the care package on a clarification summary — the selector is the SUMMARY uuid.",
                "verbs" : [
                  "CARE_PACKAGE_OPEN"
                ]
              },
              {
                "is_write" : true,
                "op" : "package_write",
                "required_params" : [
                  "package_uuid",
                  "kind"
                ],
                "summary" : "Add ONE ref while building: a dope code, a kbite file, or a curated exploration COPY.",
                "verbs" : [
                  "CARE_PACKAGE_REF_ADD"
                ]
              },
              {
                "is_write" : true,
                "op" : "package_close",
                "required_params" : [
                  "package_uuid",
                  "expected_version",
                  "clarified_intent"
                ],
                "summary" : "Seal the package with the clarified intent — building → ready. The primary's call.",
                "verbs" : [
                  "CARE_PACKAGE_COMPLETE"
                ]
              },
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes",
                    "ref_uuid"
                  ],
                  "retryWith" : "cde_rpir_clarify op=package_get with cursor = page.next_cursor; ref_uuid for one body"
                },
                "op" : "package_get",
                "required_params" : [

                ],
                "summary" : "The sealed package on its own: the intent, its refs, and the curated copies as a stub roster.",
                "verbs" : [
                  "CARE_PACKAGE_GET"
                ]
              }
            ],
            "refuses" : false,
            "schema" : {
              "properties" : {
                "agent_id" : {
                  "description" : "Your own agent id, so two agents cannot share one list. Ops write_questions, write_notes.",
                  "type" : "string"
                },
                "agent_name" : {
                  "description" : "Who is writing, for the record. Ops write_questions, write_notes.",
                  "type" : "string"
                },
                "answer_text" : {
                  "description" : "Op answer: what the human said, in full — including WHY, since a bare option pick loses the reasoning.",
                  "type" : "string"
                },
                "body" : {
                  "description" : "Op write_notes: the note text. Op package_write: the curated exploration body, written out again with more intent — copy and sharpen what was already found, do not go exploring again.",
                  "type" : "string"
                },
                "clarified_intent" : {
                  "description" : "Op package_close: what was decided, in full — what was chosen, and what was ruled out and why. This is the only place it is written down.",
                  "type" : "string"
                },
                "confused_entity_type" : {
                  "description" : "Op write_notes: exploration_finding | briefing | question | other.",
                  "type" : "string"
                },
                "confused_entity_uuid" : {
                  "description" : "Op write_notes: soft ref to the confusing entity, by uuid.",
                  "type" : "string"
                },
                "cursor" : {
                  "description" : "Ops get, package_get: page.next_cursor from the previous call (opaque). Omit for the first page.",
                  "type" : "string"
                },
                "dope_code" : {
                  "description" : "Op package_write, kind dope. Dot-path CODES like `domain.entity.property`. Never uuids, never file paths.",
                  "type" : "string"
                },
                "expected_version" : {
                  "description" : "The version you based this write on. On a conflict, re-read, take the new version and retry — that is a normal outcome, not a failure. Ops answer, seal, finalize, package_close.",
                  "type" : "integer"
                },
                "file_path" : {
                  "description" : "Op package_write, kind exploration: the repo-relative anchor.",
                  "type" : "string"
                },
                "kbite_file_uuid" : {
                  "description" : "Op package_write, kind kbite. Kbite file uuids, not codes and not paths.",
                  "type" : "string"
                },
                "kind" : {
                  "description" : "Op package_write: what sort of ref this is.",
                  "enum" : [
                    "dope",
                    "kbite",
                    "exploration"
                  ],
                  "type" : "string"
                },
                "note" : {
                  "description" : "Op package_write, kind dope: the curatorial note on the ref.",
                  "type" : "string"
                },
                "note_uuid" : {
                  "description" : "Op get: return exactly this note in full and nothing else.",
                  "type" : "string"
                },
                "note_weight_max" : {
                  "description" : "Op get: only return notes this important or better, 0 to 999. Use a small number to keep the answer short.",
                  "maximum" : 999,
                  "minimum" : 0,
                  "type" : "integer"
                },
                "op" : {
                  "description" : "Which clarification move to make. Every other argument belongs to one op; pass only that op's arguments.",
                  "enum" : [
                    "open",
                    "write_questions",
                    "write_notes",
                    "answer",
                    "seal",
                    "finalize",
                    "get",
                    "package_open",
                    "package_write",
                    "package_close",
                    "package_get"
                  ],
                  "type" : "string"
                },
                "options" : {
                  "description" : "Op write_questions: the answers to offer, in order. Write real alternatives with their trade-offs, not yes/no.",
                  "items" : {
                    "type" : "string"
                  },
                  "type" : "array"
                },
                "package_uuid" : {
                  "description" : "The care package uuid. Ops package_write, package_close.",
                  "type" : "string"
                },
                "page_bytes" : {
                  "description" : "Ops get, package_get: page budget in bytes (default 30000, max 45000).",
                  "type" : "integer"
                },
                "prompt_uuid" : {
                  "description" : "Explicit prompt uuid (omit to resolve YOUR workflow's prompt). Ops open, get, package_get.",
                  "type" : "string"
                },
                "question" : {
                  "description" : "Op write_questions: the question, written so a human can answer it without reading code.",
                  "type" : "string"
                },
                "question_uuid" : {
                  "description" : "Op answer: which question was answered. Op write_notes: attach the note to an answered question.",
                  "type" : "string"
                },
                "ref_uuid" : {
                  "description" : "Op package_get: read exactly this exploration ref's curated body in full, the rest as stubs.",
                  "type" : "string"
                },
                "selected_option_uuids" : {
                  "description" : "Op answer: which offered options they picked, by uuid.",
                  "items" : {
                    "type" : "string"
                  },
                  "type" : "array"
                },
                "skip" : {
                  "description" : "Op answer: true if the question was deliberately not asked — malformed, superseded or moot. The record keeps it either way.",
                  "type" : "boolean"
                },
                "source_finding_uuid" : {
                  "description" : "Op package_write, kind exploration: the finding this copy came from, by uuid.",
                  "type" : "string"
                },
                "summary_uuid" : {
                  "description" : "The clarification summary uuid. Ops write_questions, write_notes, seal, finalize, package_open.",
                  "type" : "string"
                },
                "title" : {
                  "description" : "Op package_write, kind exploration: a title for the copied finding.",
                  "type" : "string"
                },
                "weight" : {
                  "description" : "Op write_notes: how important, 0 is critical and 999 is ignore.",
                  "maximum" : 999,
                  "minimum" : 0,
                  "type" : "integer"
                }
              },
              "required" : [
                "op"
              ],
              "type" : "object"
            }
          },
          {
            "always_load" : false,
            "description" : "The prompt's exploration record: op open starts your finding list, op write adds ONE finding, op rank calibrates them prompt-wide, op complete seals the list with an overview, op get reads the findings back.",
            "name" : "cde_rpir_explore",
            "ops" : [
              {
                "is_write" : true,
                "op" : "open",
                "required_params" : [
                  "agent_type"
                ],
                "summary" : "Fetch-or-open an exploration summary (identity is the self-reported agent_type; 'synthesis' is the prompt-level seal row the clarifier opens once everything is ranked).",
                "verbs" : [
                  "BOT_GET",
                  "EXPLORE_OPEN"
                ]
              },
              {
                "is_write" : true,
                "op" : "write",
                "required_params" : [
                  "summary_uuid",
                  "kind",
                  "title",
                  "body",
                  "agent_name"
                ],
                "summary" : "Insert ONE exploration finding (self-rate 0=critical…999=ignore; unranked blocks the synthesis seal).",
                "verbs" : [
                  "EXPLORE_FINDING_ADD"
                ]
              },
              {
                "is_write" : true,
                "op" : "rank",
                "required_params" : [
                  "ratings"
                ],
                "summary" : "Batch-rank findings PROMPT-wide: one atomic calibrated batch across every summary. One bad pair rejects the whole batch; 0 unranked is what lets the synthesis seal pass.",
                "verbs" : [
                  "BOT_GET",
                  "EXPLORE_RANK"
                ]
              },
              {
                "is_write" : true,
                "op" : "complete",
                "required_params" : [
                  "summary_uuid",
                  "expected_version",
                  "overview"
                ],
                "summary" : "Seal a summary with its overview — your own methodology row, or the synthesis row once every finding is ranked (it refuses while anything is unranked).",
                "verbs" : [
                  "EXPLORE_COMPLETE"
                ]
              },
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes",
                    "finding_uuid"
                  ],
                  "retryWith" : "cde_rpir_explore op=get with cursor = page.next_cursor; finding_uuid for one body"
                },
                "op" : "get",
                "required_params" : [

                ],
                "summary" : "The prompt's exploration record: summaries, key files, findings inside the rating window, stubs outside it. Unranked findings are ALWAYS full rows.",
                "verbs" : [
                  "BOT_GET",
                  "EXPLORE_GET"
                ]
              }
            ],
            "refuses" : false,
            "schema" : {
              "properties" : {
                "agent_id" : {
                  "description" : "Your own agent id, so two agents cannot share one list. (open, write)",
                  "type" : "string"
                },
                "agent_name" : {
                  "description" : "Who is writing, for the record. (write)",
                  "type" : "string"
                },
                "agent_type" : {
                  "description" : "Which methodology you are (open); filter to one methodology's list (get)",
                  "enum" : [
                    "aggressive",
                    "conservative",
                    "pragmatic",
                    "alternative",
                    "general",
                    "synthesis"
                  ],
                  "type" : "string"
                },
                "body" : {
                  "description" : "Finding body (write)",
                  "type" : "string"
                },
                "cursor" : {
                  "description" : "page.next_cursor from the previous call (opaque) — omit for the first page (get)",
                  "type" : "string"
                },
                "expected_version" : {
                  "description" : "The summary version this write was based on (complete)",
                  "type" : "integer"
                },
                "file_path" : {
                  "description" : "Repo-relative anchor path (write)",
                  "type" : "string"
                },
                "finding_uuid" : {
                  "description" : "Return exactly this finding in full and nothing else (get)",
                  "type" : "string"
                },
                "full" : {
                  "description" : "Return every finding as a full row, with no stub partition (get)",
                  "type" : "boolean"
                },
                "kind" : {
                  "description" : "What kind of finding this is (write)",
                  "enum" : [
                    "persistence_model",
                    "implementation_pattern",
                    "existing_functionality",
                    "scope_creep_risk",
                    "general_relevant_change",
                    "key_file",
                    "other"
                  ],
                  "type" : "string"
                },
                "max_rating" : {
                  "description" : "Widen/narrow the full-row window to ratings 0...N (get)",
                  "type" : "integer"
                },
                "op" : {
                  "description" : "open | write | rank | complete | get",
                  "enum" : [
                    "open",
                    "write",
                    "rank",
                    "complete",
                    "get"
                  ],
                  "type" : "string"
                },
                "overview" : {
                  "description" : "Your overview narrative (complete)",
                  "type" : "string"
                },
                "page_bytes" : {
                  "description" : "Page budget in bytes (default 30000, max 45000); every array and every long text is paged inside it (get)",
                  "type" : "integer"
                },
                "prompt_uuid" : {
                  "description" : "Explicit prompt uuid (omit to resolve YOUR workflow's prompt) (open, rank, get)",
                  "type" : "string"
                },
                "rating" : {
                  "description" : "0-999 self-rating; leave it out unless you were told to rate (write)",
                  "type" : "integer"
                },
                "rating_range" : {
                  "description" : "Full-row window as A:B, inclusive rating bounds (get)",
                  "type" : "string"
                },
                "ratings" : {
                  "description" : "\"<finding-uuid>:<0-999>\" pairs, every finding at once (rank)",
                  "items" : {
                    "type" : "string"
                  },
                  "type" : "array"
                },
                "summary_uuid" : {
                  "description" : "Your exploration summary uuid (write, complete)",
                  "type" : "string"
                },
                "title" : {
                  "description" : "Finding title (write)",
                  "type" : "string"
                }
              },
              "required" : [
                "op"
              ],
              "type" : "object"
            }
          },
          {
            "always_load" : false,
            "description" : "The review record: open the complaints list, write findings, rank them, resolve them during the fix loop, seal the verdict, and read it back. Pick the part with `op`.",
            "name" : "cde_rpir_review",
            "ops" : [
              {
                "is_write" : true,
                "op" : "open",
                "required_params" : [
                  "prompt_uuid"
                ],
                "summary" : "Open the prompt's review summary. Like the other summaries, opened explicitly rather than as a side effect of a status move.",
                "verbs" : [
                  "REVIEW_OPEN"
                ]
              },
              {
                "is_write" : true,
                "op" : "write",
                "required_params" : [
                  "summary_uuid",
                  "kind",
                  "title",
                  "body",
                  "agent_name"
                ],
                "summary" : "Insert ONE review finding, self-rated 0 = critical … 999 = ignore.",
                "verbs" : [
                  "REVIEW_FINDING_ADD"
                ]
              },
              {
                "is_write" : true,
                "op" : "rank",
                "required_params" : [
                  "summary_uuid",
                  "ratings"
                ],
                "summary" : "Apply the calibrated rating batch. Version-less and atomic: ranking is CROSS-AGENT calibration and belongs to one reader, so an agent rates only its own findings and never calls this. Primary only.",
                "verbs" : [
                  "REVIEW_RANK"
                ]
              },
              {
                "is_write" : true,
                "op" : "complete",
                "required_params" : [
                  "summary_uuid",
                  "expected_version",
                  "overview",
                  "verdict"
                ],
                "summary" : "Seal the review with its overview and verdict.",
                "verbs" : [
                  "REVIEW_COMPLETE"
                ]
              },
              {
                "is_write" : true,
                "op" : "resolve",
                "required_params" : [
                  "finding_uuid",
                  "expected_version",
                  "status"
                ],
                "summary" : "Resolve ONE finding during the fix loop. `open` is deliberately not accepted — it is the initial state, so resolving TO it would move backwards through an append-only record.",
                "verbs" : [
                  "REVIEW_RESOLVE"
                ]
              },
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes",
                    "finding_uuid"
                  ],
                  "retryWith" : "cde_rpir_review op=get with cursor = page.next_cursor; finding_uuid for one body"
                },
                "op" : "get",
                "required_params" : [

                ],
                "summary" : "The prompt's review record: summary, findings inside the rating window, stubs outside it. Same window semantics as cde_rpir_explore op=get.",
                "verbs" : [
                  "REVIEW_GET"
                ]
              }
            ],
            "refuses" : false,
            "schema" : {
              "properties" : {
                "agent_id" : {
                  "description" : "Your own agent id, so two agents cannot share one list.",
                  "type" : "string"
                },
                "agent_name" : {
                  "description" : "Who is writing, for the record.",
                  "type" : "string"
                },
                "body" : {
                  "description" : "The problem itself: what breaks, and the inputs or state that make it break. A claim with no failure case is an opinion.",
                  "type" : "string"
                },
                "cursor" : {
                  "description" : "page.next_cursor from the previous call. Omit for the first page.",
                  "type" : "string"
                },
                "expected_version" : {
                  "description" : "Version of the list you read.",
                  "type" : "integer"
                },
                "file_path" : {
                  "description" : "Repo-relative file it is in, or empty.",
                  "type" : "string"
                },
                "finding_uuid" : {
                  "description" : "One finding, by uuid: the one being resolved, or the only one to read.",
                  "type" : "string"
                },
                "full" : {
                  "description" : "Return every finding as a full row, with no stub partition.",
                  "type" : "boolean"
                },
                "kind" : {
                  "description" : "What kind of problem this is, one of: correctness_bug | spec_deviation | regression_risk | security | simplification | other.",
                  "type" : "string"
                },
                "line_end" : {
                  "description" : "Last line it covers, or 0 if not line-specific.",
                  "type" : "integer"
                },
                "line_start" : {
                  "description" : "First line it covers, or 0 if not line-specific.",
                  "type" : "integer"
                },
                "max_rating" : {
                  "description" : "Only return findings this important or better, 0 to 999. Use a small number to keep the answer short.",
                  "type" : "integer"
                },
                "op" : {
                  "description" : "Which part of the review this call is: open | write | rank | complete | resolve | get.",
                  "enum" : [
                    "open",
                    "write",
                    "rank",
                    "complete",
                    "resolve",
                    "get"
                  ],
                  "type" : "string"
                },
                "overview" : {
                  "description" : "What the review found, taken as a whole.",
                  "type" : "string"
                },
                "page_bytes" : {
                  "description" : "Page budget in bytes, default 30000 and max 45000.",
                  "type" : "integer"
                },
                "prompt_uuid" : {
                  "description" : "Which prompt 's review, by uuid — omit to resolve YOUR workflow's prompt, by uuid.",
                  "type" : "string"
                },
                "rating" : {
                  "description" : "How important, 0 is most important and 999 is ignore. Leave it out unless you were told to rate; ranking is one reader's job.",
                  "type" : "integer"
                },
                "rating_range" : {
                  "description" : "Full-row window as A:B, inclusive rating bounds.",
                  "type" : "string"
                },
                "ratings" : {
                  "description" : "The calibrated batch as \"<finding-uuid>:<0-999>\" pairs (0 = critical, 999 = ignore). One bad pair rejects the whole batch.",
                  "items" : {
                    "type" : "string"
                  },
                  "type" : "array"
                },
                "status" : {
                  "description" : "How the finding was handled, one of: fixed | accepted | wont_fix. `open` is the initial state, not a resolution.",
                  "type" : "string"
                },
                "summary_uuid" : {
                  "description" : "Which complaints list to write to, by summary uuid.",
                  "type" : "string"
                },
                "title" : {
                  "description" : "Short title for the problem.",
                  "type" : "string"
                },
                "verdict" : {
                  "description" : "The verdict, one of: approved | approved_with_nits | changes_requested.",
                  "type" : "string"
                }
              },
              "required" : [
                "op"
              ],
              "type" : "object"
            }
          },
          {
            "always_load" : true,
            "description" : "Find prior work in the record by words in it.",
            "name" : "cde_rpir_search",
            "ops" : [
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes"
                  ],
                  "retryWith" : "cde_rpir_search scope=exploration with cursor = page.next_cursor"
                },
                "op" : "exploration",
                "required_params" : [
                  "query"
                ],
                "summary" : "Find old exploration findings by words in them.",
                "verbs" : [
                  "SEARCH"
                ]
              },
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes"
                  ],
                  "retryWith" : "cde_rpir_search scope=clarification with cursor = page.next_cursor"
                },
                "op" : "clarification",
                "required_params" : [
                  "query"
                ],
                "summary" : "Find old clarification questions and notes by words in them.",
                "verbs" : [
                  "SEARCH"
                ]
              },
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes"
                  ],
                  "retryWith" : "cde_rpir_search scope=architecture with cursor = page.next_cursor"
                },
                "op" : "architecture",
                "required_params" : [
                  "query"
                ],
                "summary" : "Find old architecture plans by words in them — summaries and their change rows.",
                "verbs" : [
                  "SEARCH"
                ]
              },
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes"
                  ],
                  "retryWith" : "cde_rpir_search scope=architecture_option with cursor = page.next_cursor"
                },
                "op" : "architecture_option",
                "required_params" : [
                  "query"
                ],
                "summary" : "Find one architect's proposed option by words in it.",
                "verbs" : [
                  "SEARCH"
                ]
              },
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes"
                  ],
                  "retryWith" : "cde_rpir_search scope=review with cursor = page.next_cursor"
                },
                "op" : "review",
                "required_params" : [
                  "query"
                ],
                "summary" : "Find old review findings by words in them.",
                "verbs" : [
                  "SEARCH"
                ]
              }
            ],
            "refuses" : false,
            "schema" : {
              "properties" : {
                "cursor" : {
                  "description" : "page.next_cursor from the previous call (opaque) — omit for the first page",
                  "type" : "string"
                },
                "limit" : {
                  "description" : "How many hits to return, 1 to 500.",
                  "maximum" : 500,
                  "minimum" : 1,
                  "type" : "integer"
                },
                "page_bytes" : {
                  "description" : "Page budget in bytes (default 30000, max 45000); every array and every long text is paged inside it",
                  "type" : "integer"
                },
                "query" : {
                  "description" : "Words to look for. Whole words match; misspellings find nothing.",
                  "type" : "string"
                },
                "scope" : {
                  "description" : "Which record to search.",
                  "enum" : [
                    "exploration",
                    "clarification",
                    "architecture",
                    "architecture_option",
                    "review"
                  ],
                  "type" : "string"
                },
                "session_uuid" : {
                  "description" : "Only look in this session, by uuid. Leave it out to search everything.",
                  "type" : "string"
                }
              },
              "required" : [
                "scope",
                "query"
              ],
              "type" : "object"
            }
          },
          {
            "always_load" : false,
            "description" : "The project, instance and session spine: op search finds them by name or id, op update changes one session.",
            "name" : "cde_session",
            "ops" : [
              {
                "is_write" : false,
                "narrowing" : {
                  "parameters" : [
                    "cursor",
                    "page_bytes",
                    "project_uuid",
                    "limit"
                  ],
                  "retryWith" : "cde_session op=search with cursor = page.next_cursor"
                },
                "op" : "search",
                "required_params" : [
                  "query"
                ],
                "summary" : "Find projects, instances and sessions by name or id.",
                "verbs" : [
                  "CATALOG_SEARCH"
                ]
              },
              {
                "is_write" : true,
                "op" : "update",
                "required_params" : [
                  "session_uuid",
                  "expected_version"
                ],
                "summary" : "Change one session's name, backstory or goal.",
                "verbs" : [
                  "SESSION_UPDATE"
                ]
              }
            ],
            "refuses" : false,
            "schema" : {
              "properties" : {
                "backstory" : {
                  "description" : "New backstory (update)",
                  "type" : "string"
                },
                "cursor" : {
                  "description" : "page.next_cursor from the previous call (opaque) — omit for the first page (search)",
                  "type" : "string"
                },
                "expected_version" : {
                  "description" : "The session version this write is based on (update)",
                  "type" : "integer"
                },
                "goal" : {
                  "description" : "New goal (update)",
                  "type" : "string"
                },
                "limit" : {
                  "description" : "Max hits (search)",
                  "maximum" : 500,
                  "minimum" : 1,
                  "type" : "integer"
                },
                "name" : {
                  "description" : "New name (update)",
                  "type" : "string"
                },
                "op" : {
                  "description" : "search | update",
                  "enum" : [
                    "search",
                    "update"
                  ],
                  "type" : "string"
                },
                "page_bytes" : {
                  "description" : "Page budget in bytes (default 30000, max 45000); every array and every long text is paged inside it (search)",
                  "type" : "integer"
                },
                "project_uuid" : {
                  "description" : "Restrict to one project (search)",
                  "type" : "string"
                },
                "query" : {
                  "description" : "Name or id fragment (search)",
                  "type" : "string"
                },
                "session_uuid" : {
                  "description" : "The session to update (update)",
                  "type" : "string"
                }
              },
              "required" : [
                "op"
              ],
              "type" : "object"
            }
          },
          {
            "always_load" : false,
            "description" : "Look at and change pictures. NOT BUILT YET.",
            "name" : "diagram_not_supported",
            "ops" : [

            ],
            "refuses" : true,
            "schema" : {
              "properties" : {

              },
              "required" : [

              ],
              "type" : "object"
            }
          },
          {
            "always_load" : false,
            "description" : "Touch files in the gmfs folder. NOT BUILT YET.",
            "name" : "fs_not_supported",
            "ops" : [

            ],
            "refuses" : true,
            "schema" : {
              "properties" : {

              },
              "required" : [

              ],
              "type" : "object"
            }
          },
          {
            "always_load" : false,
            "description" : "Change how the whole system behaves. NOT BUILT YET.",
            "name" : "system_not_supported",
            "ops" : [

            ],
            "refuses" : true,
            "schema" : {
              "properties" : {

              },
              "required" : [

              ],
              "type" : "object"
            }
          }
        ]
        """#
}
