// GENERATED by `gm_kernel bridge` from GmHookEvent.subagentStart — do not edit.
// Compiled with the client closure by gmk/scripts/build_plugin_binaries.sh.
// gm-closure: 
import Foundation

@main
enum GmEntry {
    static func main() { SubagentStartHook.main() }
}
