import Foundation
import GmDaemon
import GmDaemonSdk

/// PING — liveness, build identity, and the kernel's own vitals. The
/// protocol-version handshake itself runs in Server.dispatch before any handler;
/// this reports the stamped BuildInfo (generated by the SwiftPM prebuild plugin)
/// so staleness is observable.
///
/// The vitals and the writer role are measured HERE, by the process that holds
/// the database, rather than sampled by whoever is displaying them — see
/// `KernelVitalsSource` for why those are not the same process in the two shapes
/// that matter.
enum PingHandler {
    static func handle(head: EnvelopeHead, startedAt: String, startedDate: Date) throws -> HandlerResult {
        let response = PingResponse(
            daemonPid: getpid(),
            protocolVersion: GmWireProtocol.version,
            buildSha: BuildInfo.sha,
            buildDate: BuildInfo.date,
            startedAt: startedAt,
            uptimeSeconds: Int(Date().timeIntervalSince(startedDate)),
            // The vitals ride PING because it is the verb the UI already polls
            // on a watchdog — adding a second poller for a dropdown would open a
            // second connection to display numbers this one already fetches.
            residentMemoryBytes: KernelVitalsSource.residentMemoryBytes(),
            cpuPercent: KernelVitalsSource.cpuPercent(),
            writerRole: KernelVitalsSource.writerRole,
            writerBundlePath: KernelVitalsSource.writerBundlePath,
            // Answered by the process that RESOLVED it, which is the only
            // honest source. A client cannot infer this from its own
            // environment — a LaunchServices-launched app inherits none — so
            // asking is the difference between knowing and guessing.
            gmfsRoot: Paths.root.path
        )
        return try okResult(.ping, head, response)
    }
}
