import Foundation
import PackagePlugin

/// Generates `BuildInfo.swift` — the build identity `gm_hook ping` reports
/// back — INSIDE the build graph.
///
/// WHAT THIS REPLACED, and why it matters more than it sounds: the stamp used
/// to be a shell script (`stamp_build_info.sh`) that two different callers had
/// to remember to run — a developer's build script and the release workflow.
/// It wrote into a GITIGNORED `Generated/` directory, which produced a
/// fresh-clone defect: on a clean checkout `BuildInfo.swift` did not exist, so
/// the daemon target failed with an undefined-symbol error that gave no hint a
/// shell script was the missing step. Opening the project in Xcode and pressing
/// Build simply did not work, and nothing said why.
///
/// As a prebuild plugin the stamp happens because the target is being built.
/// Xcode gets it, every CI job gets it, a clean clone gets it, and the explicit
/// stamp step leaves both workflows entirely. There is no longer a way to build
/// this target WITHOUT a current stamp, which is the property that was missing.
///
/// The generated file lands in the plugin work directory, never in the source
/// tree — so there is nothing to gitignore and nothing to accidentally commit.
@main
struct StampBuildInfo: BuildToolPlugin {

    func createBuildCommands(
        context: PluginContext, target: Target
    ) async throws -> [Command] {
        let outputDir = context.pluginWorkDirectoryURL
        let output = outputDir.appending(path: "BuildInfo.swift")

        // The version pin lives at gmk/VERSION, one level above this package.
        let versionFile = context.package.directoryURL
            .deletingLastPathComponent()
            .appending(path: "VERSION")
        let version = (try? String(contentsOf: versionFile, encoding: .utf8))?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? "unknown"

        // Written as a shell one-liner rather than resolved here because the
        // PLUGIN runs once at graph-construction time while the COMMAND runs at
        // build time. Resolving the sha up here would stamp whatever commit was
        // checked out when the graph was built, which in a long-lived Xcode
        // session is not the commit being compiled.
        //
        // git is allowed to FAIL. A tarball, an exported tree or a sandboxed
        // build has no reachable .git, and `unknown` is the honest answer there
        // — the same fallback the retired shell script used. A build that
        // refused to proceed without a sha would make the stamp a liability
        // rather than a diagnostic.
        let script = """
            set -e
            sha="$(git -C "$REPO" rev-parse --short HEAD 2>/dev/null || echo unknown)"
            date="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
            mkdir -p "$(dirname "$OUT")"
            cat > "$OUT" <<EOF
            // Generated by the StampBuildInfo prebuild plugin — do not edit.
            enum BuildInfo {
                static let sha = "$sha"
                static let date = "$date"
                static let version = "$VERSION"
            }
            EOF
            """

        return [
            .prebuildCommand(
                displayName: "Stamping BuildInfo.swift for \(target.name)",
                executable: URL(fileURLWithPath: "/bin/sh"),
                arguments: ["-c", script],
                environment: [
                    "OUT": output.path(),
                    "REPO": context.package.directoryURL.path(),
                    "VERSION": version,
                ],
                outputFilesDirectory: outputDir
            )
        ]
    }
}
