// The reflection that turns the @Generable tool declarations into the served roster.

import Foundation
import FoundationModels

/// Reflects `GmAgentTools.all` into `[CdeToolSpec]` and renders
/// `CdeToolRoster.generated.swift` from it.
///
/// The declarations in `AgenticsCore/Tools` are the source of every tool name,
/// op and schema. What `GenerationSchema` encodes is a superset of what Claude
/// Code reads, so each schema is NORMALISED here — `$ref` inlined, `title`,
/// `x-order`, `additionalProperties` and `$defs` dropped — rather than served
/// as the emitter happens to spell it.
enum GmBridgeRoster {

    enum RosterError: Error, CustomStringConvertible {
        case unencodableSchema(tool: String, underlying: String)
        case notAnObjectSchema(tool: String)
        case unresolvedRef(tool: String, ref: String)
        case missingOpProperty(tool: String)
        case opMismatch(tool: String, property: String, schema: [String], declared: [String])
        case unknownKeyword(tool: String, path: String, keyword: String)

        var description: String {
            switch self {
            case let .unencodableSchema(tool, underlying):
                return "\(tool): its Arguments schema will not encode as JSON — \(underlying)"
            case .notAnObjectSchema(let tool):
                return "\(tool): its Arguments schema is not a JSON object"
            case let .unresolvedRef(tool, ref):
                return "\(tool): '\(ref)' names no entry in $defs, or refers to itself"
            case .missingOpProperty(let tool):
                return """
                    \(tool): no 'op' or 'scope' property in its Arguments — a consolidated tool \
                    must advertise the op vocabulary it answers
                    """
            case let .opMismatch(tool, property, schema, declared):
                return """
                    \(tool): the '\(property)' enum and the declared ops disagree — \
                    schema [\(schema.joined(separator: ", "))] vs ops \
                    [\(declared.joined(separator: ", "))]
                    """
            case let .unknownKeyword(tool, path, keyword):
                return """
                    \(tool).\(path).\(keyword): the emitter wrote a JSON Schema keyword this \
                    normalisation neither keeps nor knowingly drops. Decide which it is — \
                    serving it unvalidated is the v54.0.0 failure class.
                    """
            }
        }
    }

    /// The keywords that survive normalisation. Everything else the emitter
    /// writes is either presentational or unvalidated against the harness.
    private static let keptKeywords: Set<String> = [
        "type",
        "description",
        "properties",
        "required",
        "items",
        "enum",
        "anyOf",
        "minimum",
        "maximum",
    ]

    /// The keywords dropped on purpose: the ref machinery this inlines, and the
    /// presentational fields Claude Code does not read. Anything the emitter
    /// writes that is in neither set is a refusal, because a keyword nobody
    /// ruled on is a keyword served or discarded by accident.
    private static let knownDropped: Set<String> = [
        "$ref",
        "$defs",
        "title",
        "x-order",
        "additionalProperties",
    ]

    /// The property whose enum an op-bearing tool declares its vocabulary in.
    private static let opProperties = ["op", "scope"]

    /// Every declared tool as a spec, sorted by name so two runs render the
    /// same bytes whatever order the registry is written in.
    static func specs() throws -> [CdeToolSpec] {
        try GmAgentTools.all
            .sorted { $0.name < $1.name }
            .map(spec(for:))
    }

    /// The whole text of `CdeToolRoster.generated.swift`.
    static func render() throws -> String {
        let data = try CdeToolRoster.rosterEncoder.encode(specs())
        let json = String(decoding: data, as: UTF8.self)
        // The raw string's closing delimiter sets the indentation Swift strips,
        // so every JSON line carries the same prefix the delimiter does.
        let body =
            json
            .split(separator: "\n", omittingEmptySubsequences: false)
            .map { $0.isEmpty ? "" : "        " + $0 }
            .joined(separator: "\n")
        return [
            "// GENERATED by gm_kernel bridge --roster-out from AgenticsCore/Tools — do not",
            "// edit; regenerate with gmk/scripts/generate_plugin.sh",
            "",
            "enum CdeToolRoster {",
            "    static let json: String = #\"\"\"",
            body,
            "        \"\"\"#",
            "}",
            "",
        ]
        .joined(separator: "\n")
    }

    private static func spec(for tool: any GmAgentTool) throws -> CdeToolSpec {
        let declaration = type(of: tool)
        let schema = try normalisedSchema(for: tool)
        let ops = declaration.ops
        if !declaration.refuses {
            try assertOpsMatchSchema(ops.map(\.op), schema: schema, tool: tool.name)
        }
        return CdeToolSpec(
            name: tool.name,
            description: tool.description,
            alwaysLoad: declaration.alwaysLoad,
            refuses: declaration.refuses,
            schema: schema,
            ops: ops.map {
                CdeOpSpec(
                    op: $0.op,
                    verbs: $0.verbs,
                    isWrite: $0.isWrite,
                    narrowing: $0.narrowing,
                    requiredParams: $0.requiredParams,
                    summary: $0.summary
                )
            }
        )
    }

    private static func normalisedSchema(for tool: any GmAgentTool) throws -> GmJsonValue {
        let encoded: GmJsonValue
        do {
            let data = try JSONEncoder().encode(tool.parameters)
            encoded = try JSONDecoder().decode(GmJsonValue.self, from: data)
        } catch {
            throw RosterError.unencodableSchema(tool: tool.name, underlying: "\(error)")
        }
        guard case .object(let root) = encoded else {
            throw RosterError.notAnObjectSchema(tool: tool.name)
        }
        var defs: [String: GmJsonValue] = [:]
        if case .object(let declared)? = root["$defs"] { defs = declared }

        guard
            case .object(var fields) = try normalise(
                encoded,
                defs: defs,
                resolving: [],
                tool: tool.name,
                path: "arguments"
            )
        else {
            throw RosterError.notAnObjectSchema(tool: tool.name)
        }
        // A tool that takes no arguments still has to be served a shape, or the
        // harness has nothing to validate a call against.
        if fields["type"] == nil { fields["type"] = .string("object") }
        if fields["properties"] == nil { fields["properties"] = .object([:]) }
        return .object(fields)
    }

    private static func normalise(
        _ value: GmJsonValue,
        defs: [String: GmJsonValue],
        resolving: Set<String>,
        tool: String,
        path: String
    ) throws -> GmJsonValue {
        guard case .object(let fields) = value else { return value }

        if case .string(let ref)? = fields["$ref"] {
            return try inline(
                ref,
                besides: fields,
                defs: defs,
                resolving: resolving,
                tool: tool,
                path: path
            )
        }

        let recurse = { (sub: GmJsonValue, at: String) throws -> GmJsonValue in
            try normalise(sub, defs: defs, resolving: resolving, tool: tool, path: at)
        }
        var normalised: [String: GmJsonValue] = [:]
        for (keyword, field) in fields {
            guard keptKeywords.contains(keyword) else {
                guard knownDropped.contains(keyword) else {
                    throw RosterError.unknownKeyword(tool: tool, path: path, keyword: keyword)
                }
                continue
            }
            switch keyword {
            case "properties":
                guard case .object(let properties) = field else {
                    normalised[keyword] = field
                    continue
                }
                var rewritten: [String: GmJsonValue] = [:]
                for (property, sub) in properties {
                    rewritten[property] = try recurse(sub, property)
                }
                normalised[keyword] = .object(rewritten)
            case "items":
                normalised[keyword] = try recurse(field, "\(path).items")
            case "anyOf":
                guard case .array(let branches) = field else {
                    normalised[keyword] = field
                    continue
                }
                normalised[keyword] = .array(
                    try branches.map { try recurse($0, "\(path).anyOf") }
                )
            default:
                normalised[keyword] = field
            }
        }
        return .object(normalised)
    }

    /// Replace a `$ref` with the `$defs` entry it names, normalised in place.
    private static func inline(
        _ ref: String,
        besides fields: [String: GmJsonValue],
        defs: [String: GmJsonValue],
        resolving: Set<String>,
        tool: String,
        path: String
    ) throws -> GmJsonValue {
        let name = String(ref.split(separator: "/").last ?? "")
        guard let target = defs[name], !resolving.contains(name) else {
            throw RosterError.unresolvedRef(tool: tool, ref: ref)
        }
        let inlined = try normalise(
            target,
            defs: defs,
            resolving: resolving.union([name]),
            tool: tool,
            path: path
        )
        // A description written beside the `$ref` is the CALLER's wording and is
        // the one the agent should read.
        guard case .object(var merged) = inlined, let description = fields["description"] else {
            return inlined
        }
        merged["description"] = description
        return .object(merged)
    }

    /// The binding that makes the declaration one source rather than two: the
    /// enum the schema advertises and the op table the tool dispatches on must
    /// be the same list, in the same order.
    private static func assertOpsMatchSchema(
        _ declared: [String],
        schema: GmJsonValue,
        tool: String
    ) throws {
        guard case .object(let root) = schema, case .object(let properties)? = root["properties"]
        else {
            throw RosterError.missingOpProperty(tool: tool)
        }
        guard
            let property = opProperties.first(where: { properties[$0] != nil }),
            case .object(let opField)? = properties[property],
            case .array(let cases)? = opField["enum"]
        else {
            throw RosterError.missingOpProperty(tool: tool)
        }
        let advertised = cases.compactMap { value -> String? in
            guard case .string(let name) = value else { return nil }
            return name
        }
        guard advertised == declared else {
            throw RosterError.opMismatch(
                tool: tool,
                property: property,
                schema: advertised,
                declared: declared
            )
        }
    }
}
