import Foundation

/// The generated main of one executable the plugin ships: `<directory>/src/<name>.swift`.
///
/// `@main` rather than top-level code, because the file is not `main.swift` and
/// is compiled beside the client closure. The `gm-closure:` line is read by
/// `gmk/scripts/build_plugin_binaries.sh` to add source folders beyond the base
/// closure; the writer renders text only and never compiles.
struct GmBridgeSwiftMain: GmBridgeFile {

    /// `hooks` or `bin` — the executable lands beside `src/` under it.
    let directory: String

    let name: String

    /// The declaration this main was generated from, for the header.
    let origin: String

    /// The one-line call the entry makes.
    let entry: String

    /// Folders under gmk/Sources the closure needs beyond the base set.
    let closureFolders: [String]

    var relativePath: String { "\(directory)/src/\(name).swift" }

    func contents() -> String? {
        """
        // GENERATED by `gm_kernel bridge` from \(origin) — do not edit.
        // Compiled with the client closure by gmk/scripts/build_plugin_binaries.sh.
        // gm-closure: \(closureFolders.joined(separator: " "))
        import Foundation

        @main
        enum GmEntry {
            static func main() { \(entry) }
        }

        """
    }
}

/// The personalities that ship as executables inside the plugin.
enum GmBridgePersonality {

    static var sources: [GmBridgeSwiftMain] {
        GmPersonality.allCases.compactMap { personality in
            guard personality.distribution == .plugin, let entry = personality.standaloneEntry else {
                return nil
            }
            return GmBridgeSwiftMain(
                directory: "bin",
                name: personality.rawValue,
                origin: "GmPersonality.\(personality)",
                entry: entry,
                closureFolders: personality.closureFolders
            )
        }
    }
}
