import Foundation
import PackagePlugin

/// Generates `GmVersion.swift` — the ONE version symbol for the whole gmk graph
/// — inside the build graph, from `gmk/VERSION`.
///
/// It lives in the BASE package on purpose: every other package already depends
/// on `GmDaemonSdk`, so stamping here gives the version to all of them without a
/// new edge and without a second copy of this plugin. `gmDaemon`'s own
/// `StampBuildInfo` is unchanged and still stamps `sha`/`date`/`version` for the
/// build identity `gm_hook ping` reports; this is the shared PIN, not the build
/// stamp, and the two answer different questions.
///
/// As a prebuild plugin the stamp happens because the target is being built —
/// Xcode, every CI job and a clean clone all get it with no prior shell step.
/// The generated file lands in the plugin work directory, never in the source
/// tree, so there is nothing to gitignore and nothing to accidentally commit.
@main
struct StampVersion: BuildToolPlugin {

    func createBuildCommands(
        context: PluginContext, target: Target
    ) async throws -> [Command] {
        let outputDir = context.pluginWorkDirectoryURL
        let output = outputDir.appending(path: "GmVersion.swift")

        // The version pin lives at gmk/VERSION, one level above this package.
        let versionFile = context.package.directoryURL
            .deletingLastPathComponent()
            .appending(path: "VERSION")
        let version = (try? String(contentsOf: versionFile, encoding: .utf8))?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? "unknown"

        // WRITE ONLY WHEN THE CONTENT CHANGES. This is not a micro-optimisation;
        // it is the difference between a 1-second warm build and a 48-second one
        // for every package in the repository.
        //
        // A .prebuildCommand runs UNCONDITIONALLY before every build. The obvious
        // `cat > "$OUT"` therefore rewrites this file on every invocation, moving
        // its mtime even when the version is byte-identical. Release builds are
        // whole-module, so ANY moved input recompiles the ENTIRE module — and
        // GmDaemonSdk is the base package every other package depends on. One
        // unconditional write invalidated the whole graph, every time.
        //
        // Measured before the fix, universal release, nothing changed between
        // runs: gmDaemonSdk 48s / 48s / 49s, single-threaded. The control — a
        // package with no stamp plugin — was 1s warm. The delta was this write.
        //
        // Render to a sibling temp path, compare with `cmp -s`, and move only on
        // difference. The `mv` is atomic within the same directory, so a reader
        // never sees a half-written file. On no difference the temp is discarded
        // and $OUT keeps its original mtime, which is the whole point.
        let script = """
            set -e
            mkdir -p "$(dirname "$OUT")"
            cat > "$OUT.tmp" <<EOF
            // Generated by the StampVersion prebuild plugin — do not edit.
            public enum GmVersion {
                public static let current = "$VERSION"
            }
            EOF
            if cmp -s "$OUT.tmp" "$OUT" 2>/dev/null; then
                rm -f "$OUT.tmp"
            else
                mv "$OUT.tmp" "$OUT"
            fi
            """

        return [
            .prebuildCommand(
                displayName: "Stamping GmVersion.swift for \(target.name)",
                executable: URL(fileURLWithPath: "/bin/sh"),
                arguments: ["-c", script],
                environment: [
                    "OUT": output.path(),
                    "VERSION": version,
                ],
                outputFilesDirectory: outputDir
            )
        ]
    }
}
