import Foundation
import PackagePlugin

/// Generates `GmVersion.swift` — the ONE version symbol for the whole gmk graph
/// — inside the build graph, from `gmk/VERSION`.
///
/// It lives in the BASE package on purpose: every other package already depends
/// on `GmDaemonSdk`, so stamping here gives the version to all of them without a
/// new edge and without a second copy of this plugin. `gmDaemon`'s own
/// `StampBuildInfo` is unchanged and still stamps `sha`/`date`/`version` for the
/// build identity `gm_hook ping` reports; this is the shared PIN, not the build
/// stamp, and the two answer different questions.
///
/// As a prebuild plugin the stamp happens because the target is being built —
/// Xcode, every CI job and a clean clone all get it with no prior shell step.
/// The generated file lands in the plugin work directory, never in the source
/// tree, so there is nothing to gitignore and nothing to accidentally commit.
@main
struct StampVersion: BuildToolPlugin {

    func createBuildCommands(
        context: PluginContext, target: Target
    ) async throws -> [Command] {
        let outputDir = context.pluginWorkDirectoryURL
        let output = outputDir.appending(path: "GmVersion.swift")

        // The version pin lives at gmk/VERSION, one level above this package.
        let versionFile = context.package.directoryURL
            .deletingLastPathComponent()
            .appending(path: "VERSION")
        let version = (try? String(contentsOf: versionFile, encoding: .utf8))?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? "unknown"

        let script = """
            set -e
            mkdir -p "$(dirname "$OUT")"
            cat > "$OUT" <<EOF
            // Generated by the StampVersion prebuild plugin — do not edit.
            public enum GmVersion {
                public static let current = "$VERSION"
            }
            EOF
            """

        return [
            .prebuildCommand(
                displayName: "Stamping GmVersion.swift for \(target.name)",
                executable: URL(fileURLWithPath: "/bin/sh"),
                arguments: ["-c", script],
                environment: [
                    "OUT": output.path(),
                    "VERSION": version,
                ],
                outputFilesDirectory: outputDir
            )
        ]
    }
}
