import Foundation
import PackagePlugin

/// Generates `GmVersion.swift`, the ONE version symbol for the gmk graph, from `gmk/VERSION`.
/// It lives in the base package so every dependent gets it without a new edge or a second
/// plugin. This is the shared PIN; `gmDaemon`'s `StampBuildInfo` is the build identity
/// (sha, date, version) and answers a different question. A prebuild plugin stamps because
/// the target is being built, and the file lands in the plugin work directory, never the tree.
@main
struct StampVersion: BuildToolPlugin {

    func createBuildCommands(
        context: PluginContext,
        target: Target
    ) -> [Command] {
        let outputDir = context.pluginWorkDirectoryURL
        let output = outputDir.appending(path: "GmVersion.swift")

        // The version pin lives at gmk/VERSION, one level above this package.
        let versionFile = context.package.directoryURL
            .deletingLastPathComponent()
            .appending(path: "VERSION")
        let version =
            (try? String(contentsOf: versionFile, encoding: .utf8))?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? "unknown"

        // WRITE ONLY WHEN THE CONTENT CHANGES. A prebuild command runs before every build;
        // an unconditional write moves the mtime, and a moved input recompiles every
        // whole-module dependent of this base package (48 s warm instead of 1 s).
        // Render to a sibling temp path, `cmp -s`, and `mv` only on difference: the move is
        // atomic within the directory, and on no difference $OUT keeps its mtime.
        let script = """
            set -e
            mkdir -p "$(dirname "$OUT")"
            cat > "$OUT.tmp" <<EOF
            // Generated by the StampVersion prebuild plugin — do not edit.
            public enum GmVersion {
                public static let current = "$VERSION"
            }
            EOF
            if cmp -s "$OUT.tmp" "$OUT" 2>/dev/null; then
                rm -f "$OUT.tmp"
            else
                mv "$OUT.tmp" "$OUT"
            fi
            """

        return [
            .prebuildCommand(
                displayName: "Stamping GmVersion.swift for \(target.name)",
                executable: URL(fileURLWithPath: "/bin/sh"),
                arguments: ["-c", script],
                environment: [
                    "OUT": output.path(),
                    "VERSION": version,
                ],
                outputFilesDirectory: outputDir
            )
        ]
    }
}
