import Foundation
import PackagePlugin

/// Generates `BuildInfo.swift`, the build identity `gm_hook ping` reports, inside the
/// build graph. A prebuild plugin stamps because the target is being built, so Xcode,
/// a clean clone and every script get a current stamp with no prior shell step.
/// The file lands in the plugin work directory, never in the source tree.
@main
struct StampBuildInfo: BuildToolPlugin {

    func createBuildCommands(
        context: PluginContext,
        target: Target
    ) -> [Command] {
        let outputDir = context.pluginWorkDirectoryURL
        let output = outputDir.appending(path: "BuildInfo.swift")

        // The version pin lives at gmk/VERSION, beside this package's manifest.
        let versionFile = context.package.directoryURL.appending(path: "VERSION")
        let version =
            (try? String(contentsOf: versionFile, encoding: .utf8))?
            .trimmingCharacters(in: .whitespacesAndNewlines) ?? "unknown"

        // The sha and date resolve inside the COMMAND, at build time: the plugin body runs
        // once at graph construction, which in a long Xcode session is not the commit
        // being compiled. git may fail (tarball, sandbox); `unknown` is the honest stamp.
        //
        // Two properties hold together and must stay together: the date is the COMMIT
        // date, so the content is stable for a given commit, and the file is written only
        // when the content changes. A prebuild command runs before every build, and an
        // unconditional write moves the mtime and recompiles every whole-module dependent.
        let script = """
            set -e
            sha="$(git -C "$REPO" rev-parse --short HEAD 2>/dev/null || echo unknown)"
            date="$(git -C "$REPO" show -s --format=%cI HEAD 2>/dev/null || echo unknown)"
            mkdir -p "$(dirname "$OUT")"
            cat > "$OUT.tmp" <<EOF
            // Generated by the StampBuildInfo prebuild plugin — do not edit.
            enum BuildInfo {
                static let sha = "$sha"
                static let date = "$date"
                static let version = "$VERSION"
            }
            EOF
            if cmp -s "$OUT.tmp" "$OUT" 2>/dev/null; then
                rm -f "$OUT.tmp"
            else
                mv "$OUT.tmp" "$OUT"
            fi
            """

        return [
            .prebuildCommand(
                displayName: "Stamping BuildInfo.swift for \(target.name)",
                executable: URL(fileURLWithPath: "/bin/sh"),
                arguments: ["-c", script],
                environment: [
                    "OUT": output.path(),
                    "REPO": context.package.directoryURL.path(),
                    "VERSION": version,
                ],
                outputFilesDirectory: outputDir
            )
        ]
    }
}
