#!/bin/bash
set -eu
VERSION="$(tr -d '[:space:]' < "$SCRIPT_INPUT_FILE")"
REPO="$SRCROOT/.."
sha="$(git -C "$REPO" rev-parse --short HEAD 2>/dev/null || echo unknown)"
date="$(git -C "$REPO" show -s --format=%cI HEAD 2>/dev/null || echo unknown)"
mkdir -p "$DERIVED_FILE_DIR"
emit() { # $1 path, stdin content; write only when changed (mtime = recompile).
  # The script sandbox permits writes to declared outputs only, so no temp file.
  local content; content="$(cat)"
  [ -f "$1" ] && [ "$(cat "$1")" = "$content" ] && return 0
  printf '%s\n' "$content" > "$1"; }
emit "$DERIVED_FILE_DIR/GmVersion.swift" <<EOF
// Generated by scripts/stamp_build_info.sh — do not edit.
enum GmVersion { static let current = "$VERSION" }
EOF
emit "$DERIVED_FILE_DIR/BuildInfo.swift" <<EOF
// Generated by scripts/stamp_build_info.sh — do not edit.
enum BuildInfo { static let sha = "$sha"; static let date = "$date"; static let version = "$VERSION" }
EOF
