import Foundation

// MARK: - The value types that cross the boundary

/// One iTerm2 profile key/value override, applied to this session only.
///
/// The JSON encoding is iTerm2's: `json_value` is a JSON document, so a string
/// value must arrive already quoted. ``string(_:_:)`` does that, and is what
/// callers should use rather than hand-building a quoted literal.
public struct PaneProfileProperty: Sendable, Equatable {
    public let key: String
    public let jsonValue: String

    public init(key: String, jsonValue: String) {
        self.key = key
        self.jsonValue = jsonValue
    }

    /// A property whose value is a JSON string.
    public static func string(_ key: String, _ value: String) -> PaneProfileProperty {
        var escaped = ""
        escaped.reserveCapacity(value.count + 2)
        for scalar in value.unicodeScalars {
            switch scalar {
            case "\"":      escaped += "\\\""
            case "\\":      escaped += "\\\\"
            case "\n":      escaped += "\\n"
            case "\r":      escaped += "\\r"
            case "\t":      escaped += "\\t"
            case let s where s.value < 0x20:
                escaped += String(format: "\\u%04x", s.value)
            default:        escaped.unicodeScalars.append(scalar)
            }
        }
        return PaneProfileProperty(key: key, jsonValue: "\"\(escaped)\"")
    }

    /// A property whose value is a JSON boolean.
    public static func bool(_ key: String, _ value: Bool) -> PaneProfileProperty {
        PaneProfileProperty(key: key, jsonValue: value ? "true" : "false")
    }
}

/// What to open.
///
/// `profileName` may be `nil`, which means iTerm2's default profile.
public struct PaneLaunchRequest: Sendable, Equatable {
    public let profileName: String?
    public let profileProperties: [PaneProfileProperty]

    public init(profileName: String?, profileProperties: [PaneProfileProperty]) {
        self.profileName = profileName
        self.profileProperties = profileProperties
    }
}

/// What iTerm2 created.
public struct PaneSession: Sendable, Equatable {
    public let windowId: String
    public let tabId: Int32
    public let sessionId: String

    /// True when the session was created against iTerm2's DEFAULT profile.
    ///
    /// If the caller named a profile, this being true means the named one could
    /// not be resolved and the degraded rung fired: the window, directory and
    /// command are all correct, the COLOURS are not. A caller that ignores it
    /// reports a launch as fully successful when the user can see that it was
    /// not. (If the caller passed `nil`, this is simply true and says nothing
    /// went wrong.)
    public let usedDefaultProfile: Bool

    public init(windowId: String, tabId: Int32, sessionId: String, usedDefaultProfile: Bool) {
        self.windowId = windowId
        self.tabId = tabId
        self.sessionId = sessionId
        self.usedDefaultProfile = usedDefaultProfile
    }
}

/// Where a launch has got to, for a progress indicator.
public enum LaunchStage: Sendable {
    case preparing
    case startingApp
    case connecting
    case openingWindow
}

// MARK: - The façade

/// **The package's only public entry point.**
///
/// ## THE BOUNDARY, WRITTEN DOWN BECAUSE IT IS WHAT KEEPS THIS A TRANSPORT
///
/// **THIS PACKAGE IS GMCC-AGNOSTIC BY CONSTRUCTION.** It knows nothing about
/// `GM_FS_ROOT`, `gm_hook`, prompts, sessions, instances or bot tiers, and it
/// takes a READY-MADE command. That is the line that stops it becoming a second
/// home for the feature, and it is precisely why the script builder lives in
/// `gmVibesCore` — which already has `Paths`, and already knows what a prompt
/// is. If you find yourself wanting to import anything GMCC-shaped here, the
/// thing you are building belongs on the other side of this call.
///
/// **NOTHING GENERATED BY PROTOBUF EVER CROSSES THIS BOUNDARY.** Every type in
/// this file is a hand-written `Sendable` value type, so `gmVibesCore` never
/// imports SwiftProtobuf and the pin stays confined to this package exactly as
/// GRDB is confined to `gmDaemon`.
///
/// ## The three isolation layers
///
/// ```
/// @MainActor  ITerm2Launcher   this file — the only thing a caller touches
/// @MainActor  ITerm2App        AppKit only: resolve bundle, launch, activate
///    actor    ITerm2Client     socket only, CUSTOM EXECUTOR, no AppKit
/// ```
@MainActor
public enum ITerm2Launcher {
    /// Open a new iTerm2 window running a command, and bring iTerm2 forward.
    ///
    /// `progress` is a plain `@Sendable` closure rather than an `AsyncStream`:
    /// one closure, no new machinery, and the caller does the MainActor hop
    /// where it already is.
    @discardableResult
    public static func launchPane(
        _ request: PaneLaunchRequest,
        progress: @Sendable (LaunchStage) -> Void = { _ in }
    ) async throws(ITerm2Error) -> PaneSession {
        progress(.preparing)

        try await ITerm2App.ensureRunning(progress: progress)

        progress(.connecting)
        let session = try await ITerm2Client.shared.createWindow(request)

        progress(.openingWindow)
        // Mandatory — see the comment on `ITerm2App.activate()`. The API server
        // suppresses cross-app activation on every session it creates, so
        // without this a successful launch reads as a no-op.
        ITerm2App.activate()

        return session
    }

    /// Open a new iTerm2 window at a directory, carrying NO command.
    ///
    /// For "show me this folder", where the profile's own command is what
    /// should run. The caller supplies the working directory as a profile
    /// property; this signature exists so that case does not have to pretend it
    /// has a command.
    @discardableResult
    public static func openWindow(
        profileName: String?,
        profileProperties: [PaneProfileProperty] = []
    ) async throws(ITerm2Error) -> PaneSession {
        try await launchPane(
            PaneLaunchRequest(profileName: profileName, profileProperties: profileProperties)
        )
    }

    /// Drop the shared connection. Nothing requires this; it exists so a caller
    /// that knows it is done can stop holding a socket open.
    public static func disconnect() async {
        await ITerm2Client.shared.disconnect()
    }
}
