#!/bin/bash

# GMCC daemon build + install script
#
# Builds the GMCCDaemon Swift package (plugins/gmcc/daemon/) in release mode
# and installs the gmcc_daemon + gmcc_mcp + gmcc_hook binaries into ~/gmcc/bin/.
#
# Usage:
#   build_daemon.sh            # rebuild only if sources are newer than the
#                              # installed binaries (find -newer staleness check)
#   build_daemon.sh --force    # always rebuild
#
# ${CLAUDE_PLUGIN_ROOT} is only resolved inside hook/command strings, so —
# like gmcc_session_startup.sh — the plugin root is derived from this script's own
# location with the dirname trick.

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
GMCC_PLUGIN_DIR="$(dirname "$SCRIPT_DIR")"
DAEMON_PKG="$GMCC_PLUGIN_DIR/daemon"

GMCC_RUNTIME="${GMCC_ROOT:-$HOME/gmcc}"
GMCC_BIN="$GMCC_RUNTIME/bin"

if [ ! -f "$DAEMON_PKG/Package.swift" ]; then
    echo "[GMB] ERROR: daemon package not found at $DAEMON_PKG" >&2
    exit 1
fi

if ! command -v swift >/dev/null 2>&1; then
    echo "[GMB] ERROR: swift toolchain not found — install Xcode command line tools" >&2
    exit 1
fi

# --- staleness check --------------------------------------------------------
# Rebuild when either installed binary is missing, or any package source is
# newer than the installed gmcc_daemon.
needs_build=0
if [ "$1" = "--force" ]; then
    needs_build=1
elif [ ! -x "$GMCC_BIN/gmcc_daemon" ] || [ ! -x "$GMCC_BIN/gmcc_mcp" ] || [ ! -x "$GMCC_BIN/gmcc_hook" ]; then
    needs_build=1
elif [ -n "$(find "$DAEMON_PKG/Sources" "$DAEMON_PKG/Package.swift" -newer "$GMCC_BIN/gmcc_daemon" -print -quit 2>/dev/null)" ]; then
    needs_build=1
fi

if [ "$needs_build" -eq 0 ]; then
    echo "[GMB] daemon binaries up to date at $GMCC_BIN"
    exit 0
fi

# --- BuildInfo stamping -----------------------------------------------------
# Generated (gitignored) build identity returned by `gmcc_hook ping` / PING. A dev
# placeholder is written by hand once so bare `swift build` compiles; this
# overwrites it with the real sha + date before every scripted build.
GENERATED_DIR="$DAEMON_PKG/Sources/gmcc_daemon/Generated"
mkdir -p "$GENERATED_DIR"
BUILD_SHA="$(git -C "$DAEMON_PKG" rev-parse --short HEAD 2>/dev/null || echo unknown)"
BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"
cat > "$GENERATED_DIR/BuildInfo.swift" <<EOF
// Generated by scripts/build_daemon.sh — do not edit.
enum BuildInfo {
    static let sha = "$BUILD_SHA"
    static let date = "$BUILD_DATE"
}
EOF

# --- build ------------------------------------------------------------------
echo "[GMB] building GMCCDaemon (release)..."
swift build -c release --package-path "$DAEMON_PKG"

BIN_DIR="$(swift build -c release --package-path "$DAEMON_PKG" --show-bin-path)"

# --- install ----------------------------------------------------------------
# rm before cp: overwriting a signed Mach-O in place leaves the kernel's
# code-signature cache pointing at the old inode contents, and the next exec
# of the binary dies with SIGKILL (exit 137, no output). Fresh inodes only.
mkdir -p "$GMCC_BIN"
# The retired CLI is removed from the runtime bin too: a stale `gm` left on
# disk is a binary that still opens the socket and still writes.
rm -f "$GMCC_BIN/gm"
rm -f "$GMCC_BIN/gmcc_daemon" "$GMCC_BIN/gmcc_mcp" "$GMCC_BIN/gmcc_hook"
cp "$BIN_DIR/gmcc_daemon" "$GMCC_BIN/gmcc_daemon"
cp "$BIN_DIR/gmcc_mcp" "$GMCC_BIN/gmcc_mcp"
cp "$BIN_DIR/gmcc_hook" "$GMCC_BIN/gmcc_hook"
chmod +x "$GMCC_BIN/gmcc_daemon" "$GMCC_BIN/gmcc_mcp" "$GMCC_BIN/gmcc_hook"

echo "[GMB] installed:"
echo "  $GMCC_BIN/gmcc_daemon"
echo "  $GMCC_BIN/gmcc_mcp"
echo "  $GMCC_BIN/gmcc_hook"
echo ""
echo "[GMB] a running daemon (if any) is now stale — restart it (launchctl kickstart, or stop it and let the next client autostart)"
echo "      (the protocol handshake auto-retires it only across a wire-version bump)"
