#!/bin/bash

# Writes daemon/Sources/gmcc_daemon/Generated/BuildInfo.swift — the gitignored
# build identity `gmcc_hook ping` reports back.
#
# WHY THIS IS ITS OWN SCRIPT: two things build this package — build_daemon.sh on
# a developer's machine and the release workflow in CI — and both must stamp the
# SAME shape. When each carried its own heredoc they were free to drift, and a
# drifted stamp is invisible until someone compares a CI `ping` against a local
# one and finds the fields disagree. One writer, two callers.
#
# Usage: stamp_build_info.sh <daemon-package-path> [version]
#   version defaults to the contents of <pkg>/VERSION.

set -e

DAEMON_PKG="$1"
if [ -z "$DAEMON_PKG" ] || [ ! -f "$DAEMON_PKG/Package.swift" ]; then
    echo "[GMB] stamp_build_info.sh: not a daemon package: ${DAEMON_PKG:-<empty>}" >&2
    exit 1
fi

VERSION="$2"
if [ -z "$VERSION" ]; then
    VERSION="$(cat "$DAEMON_PKG/VERSION" 2>/dev/null || echo unknown)"
fi

BUILD_SHA="$(git -C "$DAEMON_PKG" rev-parse --short HEAD 2>/dev/null || echo unknown)"
BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

GENERATED_DIR="$DAEMON_PKG/Sources/gmcc_daemon/Generated"
mkdir -p "$GENERATED_DIR"
cat > "$GENERATED_DIR/BuildInfo.swift" <<EOF
// Generated by scripts/stamp_build_info.sh — do not edit.
enum BuildInfo {
    static let sha = "$BUILD_SHA"
    static let date = "$BUILD_DATE"
    static let version = "$VERSION"
}
EOF
